begin;

create extension if not exists citext;

create table if not exists public.plvip_player_profiles (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null unique references auth.users(id) on delete cascade,
  founding_player_number bigint generated by default as identity (start with 1001 increment by 1) unique,
  username citext not null unique,
  display_name text not null,
  avatar_url text,
  country text,
  bio text,
  main_games text[] not null default '{}',
  platforms text[] not null default '{}',
  play_style text,
  social text,
  is_public boolean not null default true,
  moderation_status text not null default 'pending' check (moderation_status in ('pending','approved','rejected','suspended')),
  fair_play_status text not null default 'good' check (fair_play_status in ('good','review','restricted')),
  profile_completion smallint not null default 0 check (profile_completion between 0 and 100),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  approved_at timestamptz,
  approved_by uuid references auth.users(id)
);

create table if not exists public.plvip_badges (
  id uuid primary key default gen_random_uuid(),
  slug citext not null unique,
  name text not null,
  description text not null,
  icon text not null default '◆',
  category text not null default 'community',
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.plvip_player_badges (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid not null references public.plvip_player_profiles(id) on delete cascade,
  badge_id uuid not null references public.plvip_badges(id) on delete cascade,
  awarded_at timestamptz not null default now(),
  awarded_by uuid references auth.users(id),
  note text,
  unique(profile_id,badge_id)
);

create table if not exists public.plvip_challenges (
  id uuid primary key default gen_random_uuid(),
  slug citext not null unique,
  title text not null,
  summary text not null,
  instructions text not null,
  points_reward integer not null default 0 check (points_reward between 0 and 100000),
  status text not null default 'draft' check (status in ('draft','open','closed','archived')),
  opens_at timestamptz,
  closes_at timestamptz,
  published boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id),
  check (closes_at is null or opens_at is null or closes_at > opens_at)
);

create table if not exists public.plvip_challenge_submissions (
  id uuid primary key default gen_random_uuid(),
  challenge_id uuid not null references public.plvip_challenges(id) on delete cascade,
  profile_id uuid not null references public.plvip_player_profiles(id) on delete cascade,
  response_text text not null,
  evidence_url text,
  status text not null default 'submitted' check (status in ('submitted','approved','rejected','needs_review')),
  submitted_at timestamptz not null default now(),
  reviewed_at timestamptz,
  reviewed_by uuid references auth.users(id),
  unique(challenge_id,profile_id)
);

create table if not exists public.plvip_points_ledger (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid not null references public.plvip_player_profiles(id) on delete cascade,
  amount integer not null check (amount between -100000 and 100000),
  reason text not null,
  source_type text not null default 'admin',
  source_id uuid,
  created_at timestamptz not null default now(),
  created_by uuid references auth.users(id),
  unique(profile_id,source_type,source_id)
);

create table if not exists public.plvip_announcements (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  body text not null,
  status text not null default 'draft' check (status in ('draft','published','archived')),
  published_at timestamptz,
  created_at timestamptz not null default now(),
  created_by uuid references auth.users(id)
);

create index if not exists plvip_profiles_public_idx on public.plvip_player_profiles(moderation_status,is_public,founding_player_number);
create index if not exists plvip_points_profile_idx on public.plvip_points_ledger(profile_id,created_at desc);
create index if not exists plvip_challenges_public_idx on public.plvip_challenges(published,status,opens_at);
create index if not exists plvip_submissions_profile_idx on public.plvip_challenge_submissions(profile_id,submitted_at desc);

create or replace function public.plvip_set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.plvip_calculate_profile_completion()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  completed integer := 0;
begin
  if nullif(trim(new.display_name),'') is not null then completed := completed + 15; end if;
  if nullif(trim(new.country),'') is not null then completed := completed + 10; end if;
  if nullif(trim(new.bio),'') is not null then completed := completed + 15; end if;
  if nullif(trim(new.avatar_url),'') is not null then completed := completed + 15; end if;
  if coalesce(array_length(new.main_games,1),0) > 0 then completed := completed + 20; end if;
  if coalesce(array_length(new.platforms,1),0) > 0 then completed := completed + 15; end if;
  if nullif(trim(new.play_style),'') is not null then completed := completed + 5; end if;
  if nullif(trim(new.social),'') is not null then completed := completed + 5; end if;
  new.profile_completion := completed;
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists plvip_profiles_completion on public.plvip_player_profiles;
create trigger plvip_profiles_completion
before insert or update on public.plvip_player_profiles
for each row execute function public.plvip_calculate_profile_completion();

drop trigger if exists plvip_challenges_updated_at on public.plvip_challenges;
create trigger plvip_challenges_updated_at
before update on public.plvip_challenges
for each row execute function public.plvip_set_updated_at();

insert into public.plvip_badges(slug,name,description,icon,category)
values
  ('founding-player','Founding Player','Awarded to the first generation of Players League members.','★','founding'),
  ('profile-complete','Profile Complete','Awarded for completing every core player-profile field.','✓','progress'),
  ('first-challenge','First Challenge','Awarded after an approved first community challenge.','⚑','challenge'),
  ('fair-player','Fair Player','Awarded for positive participation and fair play.','◇','community')
on conflict (slug) do update set
  name=excluded.name,
  description=excluded.description,
  icon=excluded.icon,
  category=excluded.category,
  active=true;

insert into public.plvip_challenges(slug,title,summary,instructions,points_reward,status,published)
values (
  'the-game-that-shaped-me',
  'The Game That Shaped Me',
  'Tell the league which game influenced you most and what it taught you.',
  'Write a short, genuine response about the game, moment or community that shaped your identity as a player. Do not include private information.',
  100,
  'open',
  true
)
on conflict (slug) do nothing;

create or replace function public.plvip_award_founding_badge()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  founding_badge uuid;
begin
  select id into founding_badge from public.plvip_badges where slug='founding-player' limit 1;
  if founding_badge is not null then
    insert into public.plvip_player_badges(profile_id,badge_id,note)
    values(new.id,founding_badge,'Automatically awarded when the Founding Player profile was created.')
    on conflict do nothing;
  end if;
  insert into public.plvip_points_ledger(profile_id,amount,reason,source_type,source_id)
  values(new.id,50,'Created a Founding Player profile','profile',new.id)
  on conflict do nothing;
  return new;
end;
$$;

drop trigger if exists plvip_profiles_founding_badge on public.plvip_player_profiles;
create trigger plvip_profiles_founding_badge
after insert on public.plvip_player_profiles
for each row execute function public.plvip_award_founding_badge();

alter table public.plvip_player_profiles enable row level security;
alter table public.plvip_badges enable row level security;
alter table public.plvip_player_badges enable row level security;
alter table public.plvip_challenges enable row level security;
alter table public.plvip_challenge_submissions enable row level security;
alter table public.plvip_points_ledger enable row level security;
alter table public.plvip_announcements enable row level security;

revoke all on public.plvip_player_profiles from anon, authenticated;
revoke all on public.plvip_badges from anon, authenticated;
revoke all on public.plvip_player_badges from anon, authenticated;
revoke all on public.plvip_challenges from anon, authenticated;
revoke all on public.plvip_challenge_submissions from anon, authenticated;
revoke all on public.plvip_points_ledger from anon, authenticated;
revoke all on public.plvip_announcements from anon, authenticated;

grant select on public.plvip_player_profiles to anon, authenticated;
grant insert(user_id,username,display_name,avatar_url,country,bio,main_games,platforms,play_style,social,is_public) on public.plvip_player_profiles to authenticated;
grant update(username,display_name,avatar_url,country,bio,main_games,platforms,play_style,social,is_public) on public.plvip_player_profiles to authenticated;
grant select on public.plvip_badges, public.plvip_player_badges, public.plvip_challenges, public.plvip_announcements to anon, authenticated;
grant select,insert(response_text,evidence_url,challenge_id,profile_id),update(response_text,evidence_url) on public.plvip_challenge_submissions to authenticated;
grant select on public.plvip_challenge_submissions, public.plvip_points_ledger to authenticated;

drop policy if exists plvip_profiles_public_read on public.plvip_player_profiles;
create policy plvip_profiles_public_read on public.plvip_player_profiles
for select using (
  (is_public=true and moderation_status='approved')
  or auth.uid()=user_id
  or public.current_user_is_admin()
);

drop policy if exists plvip_profiles_insert_own on public.plvip_player_profiles;
create policy plvip_profiles_insert_own on public.plvip_player_profiles
for insert to authenticated with check (auth.uid()=user_id);

drop policy if exists plvip_profiles_update_own on public.plvip_player_profiles;
create policy plvip_profiles_update_own on public.plvip_player_profiles
for update to authenticated using (auth.uid()=user_id or public.current_user_is_admin())
with check (auth.uid()=user_id or public.current_user_is_admin());

drop policy if exists plvip_badges_public_read on public.plvip_badges;
create policy plvip_badges_public_read on public.plvip_badges
for select using (active=true or public.current_user_is_admin());

drop policy if exists plvip_player_badges_public_read on public.plvip_player_badges;
create policy plvip_player_badges_public_read on public.plvip_player_badges
for select using (
  exists(
    select 1 from public.plvip_player_profiles p
    where p.id=profile_id
      and ((p.is_public=true and p.moderation_status='approved') or p.user_id=auth.uid())
  )
  or public.current_user_is_admin()
);

drop policy if exists plvip_challenges_public_read on public.plvip_challenges;
create policy plvip_challenges_public_read on public.plvip_challenges
for select using (published=true or public.current_user_is_admin());

drop policy if exists plvip_submissions_own_read on public.plvip_challenge_submissions;
create policy plvip_submissions_own_read on public.plvip_challenge_submissions
for select to authenticated using (
  exists(select 1 from public.plvip_player_profiles p where p.id=profile_id and p.user_id=auth.uid())
  or public.current_user_is_admin()
);

drop policy if exists plvip_submissions_own_insert on public.plvip_challenge_submissions;
create policy plvip_submissions_own_insert on public.plvip_challenge_submissions
for insert to authenticated with check (
  exists(select 1 from public.plvip_player_profiles p where p.id=profile_id and p.user_id=auth.uid())
  and exists(
    select 1 from public.plvip_challenges c
    where c.id=challenge_id and c.published=true and c.status='open'
      and (c.opens_at is null or c.opens_at<=now())
      and (c.closes_at is null or c.closes_at>now())
  )
);

drop policy if exists plvip_submissions_own_update on public.plvip_challenge_submissions;
create policy plvip_submissions_own_update on public.plvip_challenge_submissions
for update to authenticated using (
  status='submitted'
  and exists(select 1 from public.plvip_player_profiles p where p.id=profile_id and p.user_id=auth.uid())
)
with check (
  status='submitted'
  and exists(select 1 from public.plvip_player_profiles p where p.id=profile_id and p.user_id=auth.uid())
);

drop policy if exists plvip_points_own_read on public.plvip_points_ledger;
create policy plvip_points_own_read on public.plvip_points_ledger
for select to authenticated using (
  exists(select 1 from public.plvip_player_profiles p where p.id=profile_id and p.user_id=auth.uid())
  or public.current_user_is_admin()
);

drop policy if exists plvip_announcements_public_read on public.plvip_announcements;
create policy plvip_announcements_public_read on public.plvip_announcements
for select using (status='published' and published_at<=now() or public.current_user_is_admin());

create or replace function public.plvip_public_players(search_text text default null, result_limit integer default 60)
returns table(
  username citext,
  display_name text,
  avatar_url text,
  country text,
  bio text,
  main_games text[],
  platforms text[],
  play_style text,
  social text,
  founding_player_number bigint,
  profile_completion smallint,
  badge_count bigint,
  total_points bigint
)
language sql
stable
security definer
set search_path = public
as $$
  select
    p.username,p.display_name,p.avatar_url,p.country,p.bio,p.main_games,p.platforms,
    p.play_style,p.social,p.founding_player_number,p.profile_completion,
    count(distinct pb.badge_id)::bigint,
    coalesce(sum(distinct case when l.id is not null then l.amount else 0 end),0)::bigint
  from public.plvip_player_profiles p
  left join public.plvip_player_badges pb on pb.profile_id=p.id
  left join public.plvip_points_ledger l on l.profile_id=p.id
  where p.is_public=true and p.moderation_status='approved'
    and (
      nullif(trim(search_text),'') is null
      or p.username::text ilike '%'||trim(search_text)||'%'
      or p.display_name ilike '%'||trim(search_text)||'%'
      or coalesce(p.country,'') ilike '%'||trim(search_text)||'%'
      or array_to_string(p.main_games,' ') ilike '%'||trim(search_text)||'%'
    )
  group by p.id
  order by p.founding_player_number asc
  limit greatest(1,least(coalesce(result_limit,60),100));
$$;

create or replace function public.plvip_public_leaderboard(result_limit integer default 100)
returns table(
  rank bigint,
  username citext,
  display_name text,
  avatar_url text,
  country text,
  founding_player_number bigint,
  total_points bigint,
  badge_count bigint
)
language sql
stable
security definer
set search_path = public
as $$
  with scores as (
    select
      p.id,p.username,p.display_name,p.avatar_url,p.country,p.founding_player_number,
      coalesce(sum(l.amount),0)::bigint as total_points,
      count(distinct pb.badge_id)::bigint as badge_count
    from public.plvip_player_profiles p
    left join public.plvip_points_ledger l on l.profile_id=p.id
    left join public.plvip_player_badges pb on pb.profile_id=p.id
    where p.is_public=true and p.moderation_status='approved'
    group by p.id
  )
  select
    dense_rank() over(order by total_points desc,badge_count desc,founding_player_number asc),
    username,display_name,avatar_url,country,founding_player_number,total_points,badge_count
  from scores
  order by total_points desc,badge_count desc,founding_player_number asc
  limit greatest(1,least(coalesce(result_limit,100),100));
$$;

create or replace function public.plvip_public_profile(profile_username text)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  result jsonb;
begin
  select jsonb_build_object(
    'profile',jsonb_build_object(
      'username',p.username,
      'displayName',p.display_name,
      'avatarUrl',p.avatar_url,
      'country',p.country,
      'bio',p.bio,
      'mainGames',p.main_games,
      'platforms',p.platforms,
      'playStyle',p.play_style,
      'social',p.social,
      'foundingPlayerNumber',p.founding_player_number,
      'profileCompletion',p.profile_completion,
      'joinedAt',p.created_at
    ),
    'badges',coalesce((
      select jsonb_agg(jsonb_build_object('slug',b.slug,'name',b.name,'description',b.description,'icon',b.icon,'awardedAt',pb.awarded_at) order by pb.awarded_at)
      from public.plvip_player_badges pb
      join public.plvip_badges b on b.id=pb.badge_id and b.active=true
      where pb.profile_id=p.id
    ),'[]'::jsonb),
    'totalPoints',coalesce((select sum(amount) from public.plvip_points_ledger where profile_id=p.id),0),
    'approvedChallenges',(select count(*) from public.plvip_challenge_submissions where profile_id=p.id and status='approved')
  ) into result
  from public.plvip_player_profiles p
  where p.username=profile_username::citext and p.is_public=true and p.moderation_status='approved'
  limit 1;
  return result;
end;
$$;

create or replace function public.plvip_admin_moderate_profile(target_profile uuid,new_status text)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.current_user_is_admin() then raise exception 'Not authorised'; end if;
  if new_status not in ('pending','approved','rejected','suspended') then raise exception 'Invalid status'; end if;
  update public.plvip_player_profiles
  set moderation_status=new_status,
      approved_at=case when new_status='approved' then now() else approved_at end,
      approved_by=case when new_status='approved' then auth.uid() else approved_by end,
      updated_at=now()
  where id=target_profile;
end;
$$;

create or replace function public.plvip_admin_award_badge(target_profile uuid,badge_slug text,award_note text default null)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare target_badge uuid;
begin
  if not public.current_user_is_admin() then raise exception 'Not authorised'; end if;
  select id into target_badge from public.plvip_badges where slug=badge_slug::citext and active=true;
  if target_badge is null then raise exception 'Badge not found'; end if;
  insert into public.plvip_player_badges(profile_id,badge_id,awarded_by,note)
  values(target_profile,target_badge,auth.uid(),left(nullif(trim(award_note),''),500))
  on conflict(profile_id,badge_id) do update set awarded_at=now(),awarded_by=auth.uid(),note=excluded.note;
end;
$$;

create or replace function public.plvip_admin_add_points(target_profile uuid,point_amount integer,point_reason text)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.current_user_is_admin() then raise exception 'Not authorised'; end if;
  if point_amount=0 or abs(point_amount)>100000 then raise exception 'Invalid points'; end if;
  insert into public.plvip_points_ledger(profile_id,amount,reason,source_type,created_by)
  values(target_profile,point_amount,left(trim(point_reason),300),'admin',auth.uid());
end;
$$;

create or replace function public.plvip_admin_review_submission(target_submission uuid,new_status text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  submission_record public.plvip_challenge_submissions%rowtype;
  reward integer;
  badge uuid;
begin
  if not public.current_user_is_admin() then raise exception 'Not authorised'; end if;
  if new_status not in ('approved','rejected','needs_review') then raise exception 'Invalid status'; end if;
  select * into submission_record from public.plvip_challenge_submissions where id=target_submission for update;
  if not found then raise exception 'Submission not found'; end if;
  update public.plvip_challenge_submissions set status=new_status,reviewed_at=now(),reviewed_by=auth.uid() where id=target_submission;
  if new_status='approved' then
    select points_reward into reward from public.plvip_challenges where id=submission_record.challenge_id;
    insert into public.plvip_points_ledger(profile_id,amount,reason,source_type,source_id,created_by)
    values(submission_record.profile_id,coalesce(reward,0),'Approved community challenge','challenge',submission_record.id,auth.uid())
    on conflict(profile_id,source_type,source_id) do nothing;
    select id into badge from public.plvip_badges where slug='first-challenge';
    if badge is not null then
      insert into public.plvip_player_badges(profile_id,badge_id,awarded_by,note)
      values(submission_record.profile_id,badge,auth.uid(),'Awarded for an approved community challenge.')
      on conflict do nothing;
    end if;
  end if;
end;
$$;

grant execute on function public.plvip_public_players(text,integer) to anon, authenticated;
grant execute on function public.plvip_public_leaderboard(integer) to anon, authenticated;
grant execute on function public.plvip_public_profile(text) to anon, authenticated;
grant execute on function public.plvip_admin_moderate_profile(uuid,text) to authenticated;
grant execute on function public.plvip_admin_award_badge(uuid,text,text) to authenticated;
grant execute on function public.plvip_admin_add_points(uuid,integer,text) to authenticated;
grant execute on function public.plvip_admin_review_submission(uuid,text) to authenticated;

commit;
